# Generated by Django 5.1.1 on 2024-09-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_slug_research_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='research',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
