# Generated by Django 5.1.1 on 2024-09-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_slug_alter_research_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
