# Generated by Django 5.1.1 on 2024-09-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_slug_alter_research_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='research',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
