# Generated by Django 5.1.1 on 2024-10-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_remove_research_abstract_remove_research_references_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='abstract_file',
        ),
        migrations.RemoveField(
            model_name='research',
            name='references_file',
        ),
        migrations.AddField(
            model_name='research',
            name='abstract',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='research',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='research',
            name='content',
            field=models.FileField(blank=True, null=True, upload_to='research/abstracts/'),
        ),
    ]
