# Generated by Django 5.1.1 on 2024-10-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_remove_research_abstract_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='content',
        ),
        migrations.AddField(
            model_name='research',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='research/content/'),
        ),
    ]
