# Generated by Django 5.1.1 on 2024-10-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_research_content_research_content_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='references',
        ),
    ]
